import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader showSpinner={false} color="yellow" height={3}/>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
